Repository Eltom777/SOEN341-PicturePoint, pull requests merged in 2020-04, with the labels that each got.

#114 Follow functions
  functions/.gitignore
  picturepoint/package-lock.json
  picturepoint/package.json
  picturepoint/src/App.jsx
  picturepoint/src/UserProfile/components/ProfileCard.jsx
  picturepoint/src/UserProfile/components/Taskbar Components/Friends.jsx
  picturepoint/src/components/AddLink.js
  picturepoint/src/components/Button.jsx
  picturepoint/src/components/FollowUser.js
  picturepoint/src/components/GetFollowers.js
  picturepoint/src/components/GetFollowings.js
  picturepoint/src/components/IsFollowing.js
  picturepoint/src/components/List.jsx
  picturepoint/src/components/UnfollowUser.js
  picturepoint/src/reducers/projectReducer.js
  picturepoint/src/store/actions/linkActions.js
Labels: story

#120 likes and comments acceptance tests, reference picture #119
  Documentation/Likes and Comments/comments.png
  Documentation/Likes and Comments/liked.png
  Documentation/Likes and Comments/unliked.png
Labels: Test

#121 Acceptance test/likes comments
  README.md
Labels: documentation

#125 Acceptance test/likes comments
  picturepoint/src/Firebase/functions/checkLike.js
  picturepoint/src/Firebase/functions/getComments.js
Labels: documentation

#141 changed readme with links to tests and demo
  Documentation/Documentation_of_Features.pdf
  Documentation/SOEN_341_-_AcceptanceTest.xlsx
  README.md
Labels: documentation
